herramientas/herramientas/apps/main/urls.py
from django.conf.urls import *
from django.conf import settings

#Urls para los views del frontend del usuario visitante
urlpatterns = patterns('herramientas.apps.main.views',

	#View del home
    url(r'^$', 'inicio', name='inicio'),

    #View de empresa
    url(r'^empresa/$', 'empresa', name='empresa'),

    #Views de los productos
    url(r'^productos/(?P<palabra>[A-Z a-z]+)$', 'productos', name='productos'),
    url(r'^productos/(?P<id_producto>\d+)/$', 'producto', name='producto'),
    url(r'^productos/(?P<id_producto>\d+)/pago/$', 'pagar', name='pagar'),
    url(r'^datos/$', 'datos', name='datos'),

    #View de afiliacion
    url(r'^afiliacion/$', 'afiliacion', name='afiliacion'),

    #View de contactos
    url(r'^contactos/$', 'contactos', name='contactos'),

    #View de login de usuario
    url(r'^login/(?P<redirect>.*)$', 'loginUser', name='loginUser'),

    #View de perfil de usuario
    url(r'^perfil/$', 'perfilCompras', name='perfil'),
    url(r'^perfil/1/$', 'perfilAlquiler', name='perfil'),

    #View de login de usuario
    url(r'^logout/$', 'logoutUser', name='logoutUser'),
)

herramientas/herramientas/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#import notifications

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'herramientas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    #Urls del administrador
    url(r'^', include('herramientas.apps.administrador.urls')),

    #Urls de contenido principal
    url(r'^', include('herramientas.apps.main.urls')),

    #Notificaciones
    #url('^inbox/notifications/', include(notifications.urls)),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT,}),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

herramientas/herramientas/apps/administrador/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

#Manager del modelo de usuario
class UserManager(BaseUserManager):
	def create_user(self, nombre, apellido, correo, telefono, password, ciudad, nacionalidad, cedula, afiliado):
		if not email:
			raise ValueError("Por favor ingrese un correo válido.")

		user = self.model(
			email = self.normalize_email(correo),
			nombre = nombre,
			apellido = apellido,
			telefono = telefono,
			ciudad = ciudad,
			nacionalidad = nacionalidad,
			cedula = cedula,
			is_afiliado = afiliado,
			)
		user.set_password(password)
		user.save()
		return user

	def create_superuser(self, nombre, apellido, email, telefono, password, ciudad, nacionalidad, cedula):
		user = self.model(
			email = self.normalize_email(email),
			nombre = nombre,
			apellido = apellido,
			telefono = telefono,
			ciudad = ciudad,
			nacionalidad = nacionalidad,
			cedula = cedula,
			is_afiliado = True,
		)
		user.set_password(password)
		user.is_staff = True
		user.save()
		return user


# Definicion del usuario
class User(AbstractBaseUser):
	NAC = (
		('V', 'V'),
		('E', 'E'),
		)

	nombre = models.CharField(max_length=40)
	apellido = models.CharField(max_length=40)
	email = models.EmailField(unique=True)
	ciudad = models.CharField(max_length=40)
	telefono = models.IntegerField(max_length=20)
	nacionalidad = models.CharField(max_length=1, choices=NAC, default='V')
	cedula = models.IntegerField(max_length=10)
	is_staff = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)
	is_afiliado = models.BooleanField(default=False, blank=True)

	USERNAME_FIELD = "email"
	REQUIRED_FIELDS = ['nombre', 'apellido', 'password', 'telefono',
						'ciudad', 'nacionalidad', 'cedula']

	objects = UserManager()

	def get_full_name(self):
		return self.email


	def get_short_name(self):
		return self.email


	def __str__(self):
		return self.email

	def has_perm(self, obj=None):
		return self.is_staff

	def has_module_perms(self, package):
		return self.is_staff


#Modelo para los banners de la aplicacion
class Banner(models.Model):

	nombre = models.CharField(max_length=100)
	imagen = models.ImageField(upload_to='slide-home/')
	url = models.CharField(max_length=200)

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name = "Banner"
		verbose_name_plural = "Banners"

	def __unicode__(self):
		return u"%s" %(self.nombre)


#Modelo para las clausulas
class Clausula(models.Model):

	nombre = models.CharField(max_length=100)
	tipo = models.CharField(max_length=30, choices=(('alquiler', 'alquiler'), ('venta','venta')))
	texto = models.CharField(max_length=10000)
	archivo = models.FileField(upload_to='uploads/archivos/')
	
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name='Clausula'
		verbose_name_plural = 'Clausulas'

	def __unicode__(self):
		return u"%s" %(self.nombre)


#Modelo para las notificaciones en el admin
class Notificacion(models.Model):

	tipos = (
		('venta', 'venta'),
		('alquiler', 'alquiler'),
		('usuario', 'usuario'),
	)

	nombre = models.CharField(max_length=50)
	tipo = models.CharField(choices=tipos,max_length=20)
	id_modelo = models.CharField(max_length=10)

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name = "Notificacion"
	verbose_name_plural = "Notificaciones"

	def __unicode__(self):
		return u"%s" %(self.nombre)

herramientas/herramientas/apps/main/models.py
# -*- coding: utf-8 -*-
from django.utils.translation import gettext as _
import datetime
from django.db import models
from herramientas.apps.administrador.models import *

#Rango de anos a utilizar en las herramientas
anos = []
for n in range(1960, (datetime.datetime.now().year+1)):
    anos.append((n,n))

#Modelos de la base de datos de Alquiherramientas 2112

#Informacion de empresa
class Empresa(models.Model):

	info = models.CharField(max_length=1200)
	mision = models.CharField(max_length=800)
	vision = models.CharField(max_length=800)
	servicios = models.CharField(max_length=800)

	class Meta:
		ordering = ('info',)
		verbose_name="Empresa"
		verbose_name_plural="Empresas"

	def __unicode__(self):
		return u"Empresa"


#Informacion de afiliacion
class Afiliacion(models.Model):

	info = models.CharField(max_length=1200)
	beneficios = models.CharField(max_length=800)
	archivo = models.FileField(upload_to='uploads/archivos/')

	class Meta:
		ordering = ('info',)
		verbose_name="Afiliacion"
		verbose_name_plural="Afiliaciones"

	def __unicode__(self):
		return u"Afiliacion"


#Informacion de afiliacion
class Contactos(models.Model):

	telefonos = models.CharField(max_length=500)
	correo = models.CharField(max_length=500)

	class Meta:
		ordering = ('correo',)
		verbose_name="Contacto"
		verbose_name_plural="Contactos"

	def __unicode__(self):
		return u"Contacto"


#Estados del pais
class Estado(models.Model):
	nombre = models.CharField(max_length=30)

	class Meta:
		ordering = ('nombre',)
		verbose_name = "Estado"
		verbose_name_plural = "Estados"

	def __unicode__(self):
		return u"%s" %(self.nombre)


#Ciudaddes de las maquinarias
class Ciudad(models.Model):
	nombre = models.CharField(max_length=30)

	#Claves foraneas
	estado = models.ForeignKey(Estado)

	class Meta:
		ordering = ('nombre',)
		verbose_name = "Ciudad"
		verbose_name_plural = "Ciudades"

	def __unicode__(self):
		return u"%s" %(self.nombre)


#Zonas de las ciudades
class Zona(models.Model):
	nombre = models.CharField(max_length=30)

	#Claves foraneas
	ciudad = models.ForeignKey(Ciudad)

	class Meta:
		ordering = ('nombre',)
		verbose_name = "Zona"
		verbose_name_plural = "Zonas"

	def __unicode__(self):
		return u"%s" %(self.nombre)


#Direcciones de las herramientas publicadas
class Direccion(models.Model):
	domicilio = models.CharField(max_length=100)

	#Claves foraneas
	estado = models.ForeignKey(Estado)
	ciudad = models.ForeignKey(Ciudad)
	zona = models.ForeignKey(Zona)

	class Meta:
		ordering = ('domicilio',)
		verbose_name = "Direccion"
		verbose_name_plural = "Direcciones"

	def __unicode__(self):
		return u"%s" %(self.domicilio)


#Imagen de los anuncios que se publican
class Imagen(models.Model):
    imagen = models.ImageField(upload_to='uploads/img/', null=False)
    thumbnail = models.ImageField(upload_to='uploads/img/thumbnails/', blank=True, null=True, editable=False)
    descripcion = models.CharField(max_length=140, null=True)

    #Metodo para crear el thumbnail al momento de cear la imagen
    def create_thumbnail(self):
        # If there is no image associated with this.
        # do not create thumbnail
        if not self.imagen:
            return

        from PIL import Image
        from cStringIO import StringIO
        from django.core.files.uploadedfile import SimpleUploadedFile
        import os

        # Set our max thumbnail size in a tuple (max width, max height)
        THUMBNAIL_SIZE = (200, 200)

        # Open original photo which we want to thumbnail using PIL's Image
        imagen = Image.open(StringIO(self.imagen.read()))
        image_type = imagen.format.lower()

        imagen.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)

        # Save the thumbnail
        temp_handle = StringIO()
        imagen.save(temp_handle, image_type)
        temp_handle.seek(0)

        # Save image to a SimpleUploadedFile which can be saved into
        # ImageField
        suf = SimpleUploadedFile(os.path.split(self.imagen.name)[-1], temp_handle.read(),
                                 content_type='imagen/%s' % (image_type))
        # Save SimpleUploadedFile into image field
        self.thumbnail.save('%s_thumbnail.%s' %
                            (os.path.splitext(suf.name)[0], image_type), suf, save=False)

    def save(self):
        # create a thumbnail
        self.create_thumbnail()

        super(Imagen, self).save()

    class Meta:
        abstract = True
        ordering = ('imagen',)
        verbose_name = _('Imagen')
        verbose_name_plural = _('Imagenes')

    def __unicode__(self):
        return self.descripcion


#Categoria de cada herramienta
class Categoria(models.Model):
	nombre = models.CharField(max_length=50)

	class Meta:
		verbose_name = "Categoria"
		verbose_name_plural = "Categorias"

	def __unicode__(self):
		return u"%s" %(self.nombre)


#Marca de la herramienta
class Marca(models.Model):
	nombre = models.CharField(max_length=30)

	class Meta:
		ordering = ('nombre',)
		verbose_name = "Marca"
		verbose_name_plural = "Marcas"

	def __unicode__(self):
		return u"%s" %(self.nombre)


#Modelo de cada herramienta
class Modelo(models.Model):
	nombre = models.CharField(max_length=30)

	#Claves foraneas
	marca = models.ForeignKey(Marca)

	class Meta:
		ordering = ('nombre',)
		verbose_name = "Modelo"
		verbose_name_plural = "Modelos"

	def __unicode__(self):
		return u"%s" %(self.nombre)


#Herramienta que se vende o alquila
class Herramienta(models.Model):

	nombre = models.CharField(max_length=30)
	ano = models.IntegerField(default=datetime.datetime.now().year, choices=anos, max_length=4)

	#Claves foraneas
	categoria = models.ForeignKey(Categoria)
	marca = models.ForeignKey(Marca)
	modelo = models.ForeignKey(Modelo)

	class Meta:
		ordering = ('nombre',)
		verbose_name = "Herramienta"
		verbose_name_plural = "Herramientas"

	def __unicode__(self):
		return u"%s" %(self.nombre)


#Modelo de imagen inicial
class ImagenInicial(Imagen):

	class Meta:
		abstract = False
		verbose_name = "Imagen Inicial"
		verbose_name_plural = "Imagenes Iniciales"

	def __unicode__(self):
		return u"%s" %(self.descripcion)


# Producto de las herramientas.
class Producto(models.Model):
	titulo = models.CharField(max_length=100)
	contenido = models.CharField(max_length=10000)
	cantidad = models.IntegerField(max_length=10, default=1)
	oferta = models.BooleanField(default=False, help_text='Marcado si desea que se muestre como una oferta')
	imagen = models.ForeignKey(ImagenInicial)
	disponible = models.BooleanField(default=True)
	preguntas = models.CharField(max_length=500)
	fecha_producto = models.DateTimeField(auto_now_add=True)
	fecha_actualizacion = models.DateTimeField(auto_now=True)
	
	#Claves foraneas
	direccion = models.ForeignKey(Direccion, on_delete=models.CASCADE)
	herramienta = models.OneToOneField(Herramienta, on_delete=models.CASCADE)

	class Meta:
		ordering = ('titulo',)
		verbose_name = "Producto"
		verbose_name_plural = "Productos"

	def __pass__(self):
		return self


#Imagenes de las Productos
class ImagenProducto(Imagen):
    Producto = models.ForeignKey(Producto, related_name='imagenes')

    class Meta:
    	abstract = False
        verbose_name = "Imagen Producto"
        verbose_name_plural = "Imagenes Producto"

    def __unicode__(self):
        return u"%s" %(self.descripcion)


#Clase de alquiler de herramienta que hereda de la Producto
class Alquiler(Producto):
	dias = models.IntegerField()
	# Dos numeros decimales.
	precio = models.DecimalField(max_digits=20,decimal_places=2)
	visible = models.BooleanField(default=None)

	class Meta:
		ordering = ('dias',)
		verbose_name = "Alquiler"
		verbose_name_plural = "Alquileres"


#Clase de venta de herramienta que hereda de la Producto
class Venta(Producto):
	# Dos numeros decimales.
	precio = models.DecimalField(max_digits=20, decimal_places=2)
	visible = models.BooleanField(default=None)

	class Meta:
		ordering = ('precio',)
		verbose_name = "Venta"
		verbose_name_plural = "Ventas"


# Clase de registro de los pagos realizados.
class Pago(models.Model):
	monto = models.DecimalField(max_digits=20, decimal_places=2)
	fecha = models.DateTimeField(auto_now_add=True)
	verificado = models.BooleanField(default=False)
	cantidad = models.DecimalField(max_digits=10, decimal_places=0)
	aceptado = models.BooleanField(default=False)

	#Claves foraneas
	usuario = models.ForeignKey(User)
	producto = models.ForeignKey(Producto)

	class Meta:
		verbose_name = "Pago"
		verbose_name_plural = "Pagos"

	def __str__(self):
		pass


#Clase de transacciones de pagos de ventas
class PagoVenta(Pago):

	class Meta:
		verbose_name = "Pago Venta"
		verbose_name_plural = "Pago Ventas"

	def __str__(self):
		pass


#Clase de transacciones de pagos de alquileres
class PagoAlquiler(Pago):
	dias = models.IntegerField()

	class Meta:
		verbose_name = "Pago Alquiler"
		verbose_name_plural = "Pago Alquilers"

	def __str__(self):
		pass

herramientas/herramientas/apps/main/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import *
from django.forms.extras.widgets import *
from django.contrib.auth.forms import UserCreationForm
from django.forms.models import inlineformset_factory

#Formulario de busqueda y filtrado
class BusquedaForm(forms.Form):

	choices_alquiler = (
		('','- Venta/Alquiler -'),
		('alquiler', 'Alquiler'), 
		('venta','Venta'),
	)

	choices_precio = (
		('','- Precio -'),
		('0-10000','0 - 10.000'),
		('10000-50000','10.000 - 50.000'),
		('50000-200000','50.000 - 200.000'),
		('200000-1000000','200.000 - 1.000.000'),
		('1000000-10000000','1.000.000 - 10.000.000'),
		('10000000-10000000000000000','10.000.000 - más'),
	)

	tipo = forms.ChoiceField(choices=choices_alquiler, widget=forms.Select(), required=True)
	categoria = forms.ModelChoiceField(queryset=Categoria.objects.all(), empty_label=' - Categoria -', required=False)
	marca = forms.ModelChoiceField(queryset=Marca.objects.all(), empty_label=' - Marca -', required=False)
	estado = forms.ModelChoiceField(queryset=Estado.objects.all(), empty_label=' - Estado -', required=False)
	ano = forms.ModelChoiceField(queryset=Herramienta.objects.all().values_list('ano', flat=True).distinct().order_by('ano'), empty_label='- Año -', required=False, to_field_name="ano")
	precio = forms.ChoiceField(choices=choices_precio, widget=forms.Select(), required=False)


#Formulario para contactar a la empresa
class ContactoForm(forms.Form):
	nombre = forms.CharField(required=True)
	telefono = forms.CharField(required=True)
	correo = forms.EmailField(required=True)
	mensaje = forms.CharField(widget=forms.Textarea(), required=True)


#Formulario para vender articulos
class VentaForm(forms.Form):
	precio = forms.DecimalField(required=True)
	cantidad = forms.IntegerField(required=True,min_value=0)
	total = forms.DecimalField(required=True)
	clausulas = forms.BooleanField(required=True)


#Formulario para alquilar articulos
class AlquilerForm(forms.Form):
	precio = forms.DecimalField(required=True)
	dias = forms.IntegerField(required=True,min_value=0)
	garantia = forms.DecimalField(required=True)
	cantidad = forms.IntegerField(required=True,min_value=0)
	total = forms.DecimalField(required=True)
	clausulas = forms.BooleanField(required=True)

herramientas/templates/main/afiliacion/afiliacion.html
{% extends "main/base.html" %}
{% load main_extras %}
{% load widget_tweaks %}
{% load bootstrap3 %}
{% block scripts %}
	
    <!--Estilos-->
    <link href="{{STATIC_URL}}files/css/main/afiliacion.css" rel="stylesheet">

{% endblock scripts %}
{% block content %}

	<div class="modal fade" id="registroModalAfiliacion" tabindex="-1" role="dialog" aria-labelledby="registroModalAfiliacionLabel" aria-hidden="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <img class="img-responsive" src="{{STATIC_URL}}files/img/logo-principal.png" alt="">
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <h4 class="modal-title" id="registroModalAfiliacionLabel">Registro gratuito</h4>
                            <br>
                            <form role="form" method="POST" action=".">
                                <div class="form-group">
                                    {%csrf_token%}
                                    <div class="form-inline">
                                        <label for="id_nombre">Nombre</label>
                                        {%render_field UsuarioForm.nombre class="form-control" placeholder="Nombre"%}
                                    </div>
                                    <br>
                                    <br>
                                    <div class="form-inline">
                                        <label for="id_apellido">Apellido</label>
                                        {%render_field UsuarioForm.apellido class="form-control" placeholder="Apellido"%}
                                    </div>
                                    <br>
                                    <br>
                                    <div class="form-inline">
                                        <label for="id_apellido">Tel&eacute;fono</label>
                                        {%render_field UsuarioForm.telefono class="form-control" placeholder="Teléfono"%}
                                    </div>
                                    <br>
                                    <br>
                                    <div class="form-inline">
                                        <label for="id_email">Correo electr&oacute;nico</label>
                                        {%render_field UsuarioForm.email class="form-control" placeholder="Correo Electrónico"%}
                                    </div>
                                    <br>
                                    <br>
                                    <div class="form-inline">
                                        <label for="id_password1">Contrase&ntilde;a</label>
                                        {%render_field UsuarioForm.password1 class="form-control" placeholder="Contraseña"%}
                                    </div>
                                    <br>
                                    <br>
                                    <div class="form-inline">
                                        <label for="id_password2">Confirmaci&oacute;n contrase&ntilde;a</label>
                                        {%render_field UsuarioForm.password2 class="form-control" placeholder="Repita Contraseña"%}
                                    </div>
                                    <br>
                                    <br>
                                    <div class="form-inline" align="right">
                                        <label for="id_ciudad">Ciudad</label>
                                        {%render_field UsuarioForm.ciudad class="form-control" placeholder="Ciudad de Residencia"%}
                                    </div>
                                    <br>
                                    <br>
                                    <div class="form-inline" align="right">
                                        <label for="">Documento</label>
                                        {%render_field UsuarioForm.nacionalidad class="form-control"%}
                                        {%render_field UsuarioForm.cedula class="form-control" placeholder="Cédula"%}
                                    </div>
                                    <br>
                                    <br>
                                    <div class="form-inline" align="right">
                                        <label for="">Afiliado</label>
                                        {%render_field UsuarioForm.is_afiliado type="checkbox" checked="true"%}
                                    </div>
                                    <br>
                                    <br>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary"><strong>Registrarse</strong></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



	<h3 class="titulo"> Afiliaci&oacute;n: </h3>
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<p>
			{{afiliacion.info|linebreaks}}
			</p>
            <a data-toggle="modal" data-target="#modalClausulas">Pdf</a>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<h4>Beneficios: </h4>
			{{afiliacion.beneficios|linebreaks}}
		</div>
	</div>
	<div class="row">
		<div class="col-lg-8 col-md-8 col-sm-8">
            <button class="btn btn-default" data-toggle="modal" data-target="#registroModalAfiliacion">Afiliarse</button>
		</div>
	</div>
    <div class="modal fade" id="modalClausulas" tabindex="-1" role="dialog" aria-labelledby="modalClausulasLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Afiliaci&oacute;n</h4>
          </div>
          <div class="modal-body">
            <p>
                {{afiliacion.info|linebreaks}}
            </p>
            <p>
                Descargar archivo digital: <a href="{{afiliacion.archivo.url}}" target="_blank">Afiliaci&oacute;n.</a>
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock content %}